//
// Copyright (c) Microsoft.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//

import './globals.css'
import './styles/main.scss'

import type { Metadata } from 'next';

// import Header from '../components/Header';
import Footer from '../components/Footer';
import TelemetryHead from '../components/TelemetryHead';
import TelemetryBody from '../components/TelemetryBody';
import TelemetryScript from '../components/TelemetryScript';
import MicrosoftOpenSourceHeader from '@/components/OpenSourceHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const tempViewport = {
  title: 'Microsoft Open Source',
  description: 'Microsoft Open Source',
  robots: 'noindex, nofollow',
  metadataBase: new URL('https://opensource.microsoft.com'),
  themeColor: '#11100f',
  icons: {
    icon: [
      { url: '/assets/images/favicons/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/assets/images/favicons/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: { url: '/assets/images/favicons/apple-touch-icon.png', sizes: '180x180' },
    other: [
      { rel: 'mask-icon', url: '/assets/images/favicons/safari-pinned-tab.svg', color: '#11100f' },
      { rel: 'shortcut icon', url: '/assets/images/favicons/favicon.ico' },
    ],
  },
  // NOT_PORTING_FOR_NOW: manifest: '/assets/images/favicons/site.webmanifest',
  verification: {
    google: ['PXNcqyP34d82CBV3rvH8RwDRH5iWWb_zL-UFwp-3Ubs', 'jj6XRLurdxcqc_T28_tszxZ4M2K8TFQDPjvVRb8MLsg'],
  },
  // MS-specific tags
  other: {
    'msapplication-config': '/assets/images/favicons/browserconfig.xml',
    'msapplication-TileColor': '#11100f',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // equivalent to Jekyll's environment check (?) - TODO:
  const isProduction = process.env.NODE_ENV === 'production';

  return (
    <html lang="en">
      <head>
        {/* IE specific */}
        {/*[if IE]><meta http-equiv="cleartype" content="on" /><![endif]*/}
        
        {/* Inline script for animations */}
        <script 
          type="text/javascript" 
          dangerouslySetInnerHTML={{
            __html: `document.write('<style type="text/css">*[data-animate-in="up"], *[data-animate-in="up"], *[data-animate-in="fade"], *[data-animate-in="left"], *[data-animate-in="right"] { opacity: 0; } .tabs__content { display: none; } *[data-javascript-show="immediate"] { opacity: 1.0 }</style>');`
          }}
        />
        
        {isProduction && <TelemetryHead />}
      </head>
      <body className="page-loading no-js">
        {isProduction && <TelemetryBody />}
        
        <a className="skip-to-content" href="#content" tabIndex={1}>skip to content</a>
        
        <MicrosoftOpenSourceHeader
          site='opensource.microsoft.com'
        />
        {/*
        <Header />
        */}
        
        <main id="content" className="main page-content" aria-label="Content">
          {children}
        </main>
        
        <Footer />
        
        {/* Scripts */}
        <script src="/assets/js/gsap.min.js"></script>
        <script src="/assets/js/DrawSVGPlugin.min.js"></script>
        <script src="/assets/js/main.js"></script>
        
        {/* Production telemetry script */}
        {isProduction && <TelemetryScript />}
      </body>
    </html>
  )
}
